---
- name: "set password for the play"
  set_fact:
    ansible_ssh_pass: "{{ pi_pass }}"
  when: "{{ raspi_initial_setup_first_time_run }} == True"

- name: "Enable key based auth for root"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items:
    - "{{ ssh_users }}"
  when: "{{ raspi_initial_setup_first_time_run }} == True"

- name: "Gather facts"
  setup:
